{ lib, ... }:
[
  "蔡健雅 - Nightglow.flac"
  "周深 - Rubia.flac"
  "不才;三体宇宙 - 夜航星 (Night Voyager).flac"
  "Tielle;SawanoHiroyuki[nZk] - Cage.flac"
  "阿鲲 - 550W ; Moss.flac"
  "G.E.M.邓紫棋 - 来自天堂的魔鬼.flac"
  "杨凯琳;余枫 - 怎么还不爱 (雀跃狂爱版).mp3"
  "陈奕迅 - 孤勇者.mp3"
  "祖娅纳惜 - 孤勇者.mp3"
  "HOYO-MiX - 戏剧性反讽 A Dramatic Irony.flac"
  "HOYO-MiX - 轻涟 La vaguelette.flac"
  "HITA - 赤伶.flac"
  "HOYO-MiX - 纳塔 Natlan.flac"
  "周深 - 浮游.flac"
  "周深 - 能解答一切的答案.flac"
  "洛天依Official; 哈拉木吉 - 天上的风.flac"
  "洛天依Official; 旦增益西 - 雪山之眼.flac"
  "洛天依Official - 歌行四方.flac"
  "萨吉 - 玄鸟.flac"
  "F.I.R.;彭佳慧 - 心之火.flac"
  "刘欢 - 天地在我心 (Live).flac"
  "刘欢 - 带着地球去流浪.flac"
  "刘欢 - 我在.flac"
  "萨顶顶 - 左手指月.flac"
  "豆腐P;东方栀子 - 我将沐火而唱.flac"
  "陈姿彤 - 我的世界.flac"
  "陈姿彤 - 战争世界.flac"
  "黄霄雲 - 以我之躯.flac"
  "齐栾 - Seek The Peace feat. soratan小空（For the peace 翻自 Yisabel）（Cover 齐栾）.mp3"
  "谭晶;HOYO-MiX - 何者.flac"
  "尚雯婕 - 鹿 be free.flac"
  "HOYO-MiX - 拂晓 Proi Proi.flac"
  "Hans Zimmer - F1.flac"
]
