kind: secret
name: id_ed25519
get:
  path: kv/data/ssh
  name: id_ed25519

---

kind: secret
name: tg_token
get:
  path: kv/data/telegram
  name: token

---

kind: secret
name: tg_target
get:
  path: kv/data/telegram
  name: target

---

kind: pipeline
type: docker
name: default

steps:
  - name: nix generate config
    image: nixpkgs/nix-flakes
    environment:
      SSH_KEY:
        from_secret: id_ed25519
    commands:
      - mkdir -p $HOME/.ssh
      - echo "$SSH_KEY" > $HOME/.ssh/id_ed25519
      - nix run ".#dnscontrol" -- push

  - name: ansible deploy
    image: xddxdd/ansible
    environment:
      SSH_KEY:
        from_secret: id_ed25519
    failure: ignore
    commands:
      # Get host list
      - nslookup -type=txt hosts.lantian.pub | grep -E -o "\"(.*)\"" | tr -d "\"" > ansible_hosts
      - cat ansible_hosts

      # Install SSH key
      - echo "$SSH_KEY" > $HOME/.ssh/id_ed25519
      - chmod 600 $HOME/.ssh/id_ed25519
      # Run ansible
      - ansible-playbook -i ansible_hosts dns/ansible_deploy.yml

  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: tg_token
      to:
        from_secret: tg_target
    when:
      status:
        - success
        - failure
