[airplanes-live-mcp]
fetch.git = "https://github.com/Bellaposa/airplanes-live-mcp.git"
src.git = "https://github.com/Bellaposa/airplanes-live-mcp.git"

[anti-fooling-hot-line]
fetch.git = "https://github.com/moontide/Anti-fooling-Hot-Line.git"
src.git = "https://github.com/moontide/Anti-fooling-Hot-Line.git"

[auto-novel-addon]
fetch.url = "https://github.com/auto-novel/addon/releases/download/v$ver/addon-$ver-firefox.xpi"
src.github = "auto-novel/addon"
src.prefix = "v"

[bosl2]
fetch.github = "BelfrySCAD/BOSL2"
src.github = "BelfrySCAD/BOSL2"

[delegacy-rpz]
fetch.git = "https://codeberg.org/IPv6-Monostack/delegacy-rpz.git"
src.git = "https://codeberg.org/IPv6-Monostack/delegacy-rpz.git"

[dn42-certificate-authority-client]
fetch.url = "https://dn42.g-load.eu/about/certificate-authority/client.sh?ver=$ver"
src.webpage = "https://dn42.g-load.eu/about/certificate-authority/client.sh"
src.regex = "# Version ([0-9\\.]+)"
url.name = "client.sh"

[grafana-falconlogscale-datasource]
fetch.url = "https://github.com/grafana/falconlogscale-datasource/releases/download/v$ver/grafana-falconlogscale-datasource-$ver.zip"
src.github = "grafana/falconlogscale-datasource"
src.prefix = "v"

[grafana-yesoreyeram-infinity-datasource]
fetch.url = "https://github.com/grafana/grafana-infinity-datasource/releases/download/v$ver/yesoreyeram-infinity-datasource-$ver.zip"
src.github = "grafana/grafana-infinity-datasource"
src.prefix = "v"

[lobe-icons]
fetch.git = "https://github.com/lobehub/lobe-icons.git"
src.git = "https://github.com/lobehub/lobe-icons.git"

[mihoyo-bbs-tools]
fetch.github = "Womsxd/MihoyoBBSTools"
src.git = "https://github.com/Womsxd/MihoyoBBSTools.git"

[mpv-sockets]
fetch.github = "wis/mpvSockets"
src.git = "https://github.com/wis/mpvSockets.git"

[n8n-openai-bridge-customized]
fetch.github = "xddxdd/n8n-openai-bridge"
src.git = "https://github.com/xddxdd/n8n-openai-bridge.git"

[nmea-static-gps-server]
fetch.github = "evert/nmea-static-gps-server"
src.git = "https://github.com/evert/nmea-static-gps-server.git"

[nvidia-patch]
fetch.github = "keylase/nvidia-patch"
src.git = "https://github.com/keylase/nvidia-patch.git"

[open5gs]
fetch.github = "open5gs/open5gs"
src.github = "open5gs/open5gs"

[open5gs-freediameter]
fetch.github = "open5gs/freeDiameter"
src.git = "https://github.com/open5gs/freeDiameter.git"
src.branch = "r1.5.0"

[openspeedtest]
fetch.github = "openspeedtest/Speed-Test"
src.git = "https://github.com/openspeedtest/Speed-Test.git"

[sakura-share]
fetch.github = "xddxdd/Sakura_Launcher_GUI"
src.git = "https://github.com/xddxdd/Sakura_Launcher_GUI.git"

[um-react]
fetch.url = "https://git.um-react.app/um/um-react/releases/download/v$ver/um-react-$ver.zip"
src.webpage = "https://git.um-react.app/um/um-react/releases"
src.regex = "href=\"/um/um-react/src/tag/v([0-9\\.]+)\""

[yourls]
fetch.github = "YOURLS/YOURLS"
src.github = "YOURLS/YOURLS"

[yourls-404-if-not-found]
fetch.github = "YOURLS/404-if-not-found"
src.git = "https://github.com/YOURLS/404-if-not-found.git"

[yourls-always-302]
fetch.github = "tinjaw/Always-302"
src.git = "https://github.com/tinjaw/Always-302.git"

[yourls-dont-track-admins]
fetch.github = "dgw/yourls-dont-track-admins"
src.git = "https://github.com/dgw/yourls-dont-track-admins.git"

[yourls-login-timeout]
fetch.github = "reanimus/yourls-login-timeout"
src.git = "https://github.com/reanimus/yourls-login-timeout.git"

[yourls-sleeky]
fetch.github = "Flynntes/Sleeky"
src.git = "https://github.com/Flynntes/Sleeky"
