- hosts: all
  serial: 1
  ignore_unreachable: true
  tasks:
  - name: reboot
    ignore_errors: true
    shell: "reboot"
    async: 1
    poll: 0

  - name: wait for reboot
    ignore_errors: true
    wait_for_connection:
      connect_timeout: 10
      sleep: 10
      delay: 10
      timeout: 900
