# Deploy PowerDNS zones
- hosts: all
  gather_facts: false
  tasks:
  - name: Create directory
    file:
      path: /var/lib/zones/zones/
      state: directory
  - name: Deploy root zone file
    synchronize:
      src: ../zones/
      dest: /var/lib/zones/zones/
      checksum: yes
      delete: yes
  - name: Chown
    shell: "chown -R container:container /var/lib/zones"
  - name: Restart CoreDNS
    command: nixos-container run coredns -- systemctl restart coredns
    ignore_errors: yes
  - name: Restart Knot DNS
    command: nixos-container run coredns-knot -- knotc reload
    ignore_errors: yes
