# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, ... }:
{
  imports = [
    ../../nixos/hardware/vfio.nix
    ../../nixos/hardware/smart.nix
  ];

  boot.kernelModules = [ "qat_c3xxx" ];

  boot.loader.grub = {
    efiSupport = true;
    mirroredBoots = [
      {
        devices = [ "nodev" ];
        path = "/boot";
      }
      {
        devices = [ "nodev" ];
        path = "/boot2";
      }
    ];
  };

  networking.usePredictableInterfaceNames = lib.mkForce true;

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/317D-D6BD";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/boot2" = {
    device = "/dev/disk/by-uuid/4FD3-9083";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/16345591-4ea5-4cc6-a1ef-04f1eed48916";
    fsType = "btrfs";
    options = [
      "compress-force=zstd"
      "autodefrag"
      "nosuid"
      "nodev"
    ];
  };

  hardware.cpu.intel.updateMicrocode = true;
  hardware.enableRedistributableFirmware = true;

  lantian.vfio = {
    ids = [
      "8086:125c" # Intel I226-V
      "8086:15c4" # Intel X553
      "8086:19e3" # Intel QAT C3000 VF
    ];
    blacklistedModules = [
      "igc" # Intel I226-V
      "ixgbe" # Intel X553
      "qat_c3xxxvf" # Intel QAT C3000 VF
    ];
    isolcpus = "4-7";
  };

  systemd.services.qat-sriov = {
    description = "Enable Intel QAT SRIOV";
    wantedBy = [ "multi-user.target" ];
    after = [ "systemd-modules-load.service" ];
    requires = [ "systemd-modules-load.service" ];
    before = [
      "pve-guests.service"
      "pvedaemon.service"
    ];
    serviceConfig = {
      Type = "oneshot";
      Restart = "on-failure";
      RestartSec = "3";
    };
    script = ''
      DEVICE_PATH=/sys/devices/pci0000:00/0000:00:06.0/0000:01:00.0
      NUMVFS=$(cat "$DEVICE_PATH/sriov_totalvfs")
      echo "$NUMVFS" > "$DEVICE_PATH/sriov_numvfs"
    '';
  };
}
