# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    ../../common/system/qemu.nix
  ];

  boot.loader.grub.device = "/dev/vda"; # or "nodev" for efi only

  fileSystems."/nix" = {
    device = "/dev/vda2";
    fsType = "btrfs";
    options = [ "compress-force=zstd" ];
    neededForBoot = true;
  };

  fileSystems."/boot" = {
    device = "/dev/vda1";
    fsType = "ext4";
  };
}
