# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  ...
}:
{
  imports = [
    # ../../nixos/hardware/crashdump.nix
    ../../nixos/hardware/ecc-ram.nix
  ];

  boot.loader.grub.device = "/dev/sda"; # or "nodev" for efi only

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.kernelModules = [ "kvm-intel" ];

  # Try to fix MCE https://forum.proxmox.com/threads/server-freezes-or-restarting-automatically-mce-hardware-error.73444/
  boot.kernelParams = [
    "intel_idle.max_cstate=1"
    "intel_pstate=disable"
  ];

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/12CE-A600";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/aa948056-e78e-41bd-99cb-191b4b8db823";
    fsType = "btrfs";
    options = [
      "compress-force=zstd"
      "autodefrag"
      "nosuid"
      "nodev"
    ];
  };

  fileSystems."/var/cache" = lib.mkForce {
    device = "/dev/disk/by-uuid/7ef4355a-b9ba-4875-8dc7-31fbb1766e2b";
    fsType = "btrfs";
    options = [
      "compress-force=zstd"
      "autodefrag"
      "nosuid"
      "nodev"
    ];
  };

  powerManagement.cpuFreqGovernor = lib.mkDefault "schedutil";
  hardware.cpu.intel.updateMicrocode = true;
  hardware.enableRedistributableFirmware = true;
}
