# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, ... }:
{
  imports = [
    ../../nixos/hardware/lvm.nix
    ../../nixos/hardware/ups.nix
    ../../nixos/hardware/vfio.nix
  ];

  boot.loader.grub = {
    efiSupport = true;
    device = "nodev";
  };

  boot.zfs.extraPools = [ "nvme-zfs" ];

  networking.usePredictableInterfaceNames = lib.mkForce true;

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Try to workaround issues with passthrough P40
  boot.kernelParams = [ "video=efifb:off" ];

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/815E-3292";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/fad6832b-1bde-4bda-90ba-51520e0feef4";
    fsType = "btrfs";
    options = [
      "compress-force=zstd"
      "autodefrag"
      "nosuid"
      "nodev"
    ];
  };

  fileSystems."/mnt/nvme" = {
    device = "/dev/disk/by-uuid/e2c5bd1d-8aa8-44ae-9c2a-b8976a446b4f";
    fsType = "btrfs";
    options = [
      "compress-force=zstd"
      "autodefrag"
      "nosuid"
      "nodev"
    ];
  };

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableRedistributableFirmware = true;

  lantian.vfio = {
    ids = [
      "10de:1b38" # NVIDIA Tesla P40
      "10de:2204" # NVIDIA RTX 3090
      "10de:1aef" # NVIDIA RTX 3090 HD Audio
    ];
    blacklistedModules = [
      "nouveau"
    ];
    isolcpus = "112-127";
  };
}
