# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  ...
}:
{
  imports = [
    ../../nixos/hardware/ecc-ram.nix
    ../../nixos/hardware/nvidia/cuda-only.nix
    ../../nixos/hardware/nvidia/vgpu-extension.nix
    ../../nixos/hardware/lvm.nix
    ../../nixos/hardware/smart.nix
    ../../nixos/hardware/ups.nix
    ../../nixos/hardware/vfio.nix
  ];

  boot.loader.grub = {
    efiSupport = true;
    device = "nodev";
  };

  boot.zfs.extraPools = [ "nvme-zfs" ];

  networking.usePredictableInterfaceNames = lib.mkForce true;

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Try to workaround issues with passthrough P40
  boot.kernelParams = [ "video=efifb:off" ];

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/815E-3292";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/fad6832b-1bde-4bda-90ba-51520e0feef4";
    fsType = "btrfs";
    options = [
      "compress-force=zstd"
      "autodefrag"
      "nosuid"
      "nodev"
    ];
  };

  fileSystems."/mnt/nvme" = {
    device = "/dev/disk/by-uuid/e2c5bd1d-8aa8-44ae-9c2a-b8976a446b4f";
    fsType = "btrfs";
    options = [
      "compress-force=zstd"
      "autodefrag"
      "nosuid"
      "nodev"
    ];
  };

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableRedistributableFirmware = true;

  systemd.services.nvidia-power-limit = {
    description = "Set Power Limit for NVIDIA GPUs";
    wantedBy = [ "multi-user.target" ];
    path = [
      config.hardware.nvidia.package
      pkgs.ipmitool
    ];
    script = ''
      nvidia-smi -pl 125

      # Set P40 GPU fan to 80%
      # https://forums.servethehome.com/index.php?threads/asrock-rack-bmc-fan-control.26941/post-249035
      ipmitool raw 0x3a 0x01 0x00 0x00 0x00 0x00 0x00 0x50 0x00 0x00
    '';
    serviceConfig.Type = "oneshot";
  };

  lantian.vfio = {
    ids = [
      "10de:2204" # NVIDIA RTX 3090
      "10de:1aef" # NVIDIA RTX 3090 HD Audio
    ];
    blacklistedModules = [
      "nouveau"
    ];
    isolcpus = "112-127";
  };
}
