# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  delegacy-rpz = {
    pname = "delegacy-rpz";
    version = "b832e218db76e6e12e35d29e7cf44d6d756a46bb";
    src = fetchgit {
      url = "https://codeberg.org/IPv6-Monostack/delegacy-rpz.git";
      rev = "b832e218db76e6e12e35d29e7cf44d6d756a46bb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4g64gCs4Vgeu+f5eBNHf8lejIvF0Uon1hXj2zuSPtg0=";
    };
    date = "2025-07-18";
  };
  flaresolverr = {
    pname = "flaresolverr";
    version = "v3.3.25";
    src = fetchFromGitHub {
      owner = "FlareSolverr";
      repo = "FlareSolverr";
      rev = "v3.3.25";
      fetchSubmodules = false;
      sha256 = "sha256-AGRqJOIIePaJH0j0eyMFJ6Kddul3yXF6uw6dPMnskmY=";
    };
  };
  grafana-falconlogscale-datasource = {
    pname = "grafana-falconlogscale-datasource";
    version = "1.8.2";
    src = fetchurl {
      url = "https://github.com/grafana/falconlogscale-datasource/releases/download/v1.8.2/grafana-falconlogscale-datasource-1.8.2.zip";
      sha256 = "sha256-05cgYVq3E76maKcM+TsDV1sWlsoOITQ3vQZpyC/NA9w=";
    };
  };
  grafana-yesoreyeram-infinity-datasource = {
    pname = "grafana-yesoreyeram-infinity-datasource";
    version = "3.3.0";
    src = fetchurl {
      url = "https://github.com/grafana/grafana-infinity-datasource/releases/download/v3.3.0/yesoreyeram-infinity-datasource-3.3.0.zip";
      sha256 = "sha256-y140nf/TM4IsKl4LJsPrjtyDQJuTjsp1rfUEyS81TgY=";
    };
  };
  lobe-icons = {
    pname = "lobe-icons";
    version = "29657b5738cba8f6a5beee4a6e29b2947c29c910";
    src = fetchgit {
      url = "https://github.com/lobehub/lobe-icons.git";
      rev = "29657b5738cba8f6a5beee4a6e29b2947c29c910";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NahodrEgVuM5EtZiOiZ5QS3EAmjdzxfAVmNAprmSBzU=";
    };
    date = "2025-07-17";
  };
  mihoyo-bbs-tools = {
    pname = "mihoyo-bbs-tools";
    version = "262f2740eb94743e926c3dbfba6b99d6762d70fe";
    src = fetchFromGitHub {
      owner = "Womsxd";
      repo = "MihoyoBBSTools";
      rev = "262f2740eb94743e926c3dbfba6b99d6762d70fe";
      fetchSubmodules = false;
      sha256 = "sha256-oMGDVRSmO1Mqwy+d0euO6U1F1ux5rQ+r4lvk70PF/v4=";
    };
    date = "2025-07-15";
  };
  mpv-sockets = {
    pname = "mpv-sockets";
    version = "3b3f430074a67c63572a582847ed1fa69330c668";
    src = fetchFromGitHub {
      owner = "wis";
      repo = "mpvSockets";
      rev = "3b3f430074a67c63572a582847ed1fa69330c668";
      fetchSubmodules = false;
      sha256 = "sha256-KFv3imLuiV+APx4A8TSi2LXL5gdHNKc497fRwBubvMk=";
    };
    date = "2024-02-13";
  };
  nvidia-patch = {
    pname = "nvidia-patch";
    version = "04bd29807090f31989daea5187669d01868068ba";
    src = fetchFromGitHub {
      owner = "keylase";
      repo = "nvidia-patch";
      rev = "04bd29807090f31989daea5187669d01868068ba";
      fetchSubmodules = false;
      sha256 = "sha256-fbJQ9NLGwKxyuvmzf4CdnWleFmqK2xyHI8azw7D6q8I=";
    };
    date = "2025-07-15";
  };
  open5gs = {
    pname = "open5gs";
    version = "v2.7.6";
    src = fetchFromGitHub {
      owner = "open5gs";
      repo = "open5gs";
      rev = "v2.7.6";
      fetchSubmodules = false;
      sha256 = "sha256-2k+S+OXfdskJPtDUFSxb/+2UZcUiOZzRSSGgsEJWolc=";
    };
  };
  open5gs-freediameter = {
    pname = "open5gs-freediameter";
    version = "13f5a5996b5fa1a46ed780635c7fc6fcd09b4290";
    src = fetchFromGitHub {
      owner = "open5gs";
      repo = "freeDiameter";
      rev = "13f5a5996b5fa1a46ed780635c7fc6fcd09b4290";
      fetchSubmodules = false;
      sha256 = "sha256-S8jL+9rW9RDwQc7NU8MOzMe9/iRbshWa2QLqXoiV85Q=";
    };
    date = "2025-05-31";
  };
  openspeedtest = {
    pname = "openspeedtest";
    version = "3ec39a31ec64858642629991caf0dd14ce7c34ca";
    src = fetchFromGitHub {
      owner = "openspeedtest";
      repo = "Speed-Test";
      rev = "3ec39a31ec64858642629991caf0dd14ce7c34ca";
      fetchSubmodules = false;
      sha256 = "sha256-MBVVImy0f+MQnlAYUf77mScpdqkCKi1hdOJEM7Z7KJ0=";
    };
    date = "2024-06-04";
  };
  sakura-share = {
    pname = "sakura-share";
    version = "bf6bcb04268cbd58178da76600bcdc267355ff2b";
    src = fetchFromGitHub {
      owner = "xddxdd";
      repo = "Sakura_Launcher_GUI";
      rev = "bf6bcb04268cbd58178da76600bcdc267355ff2b";
      fetchSubmodules = false;
      sha256 = "sha256-UnRNlD1GdrMg0A6P1QpybwbjumkihZBZ5srftvixVag=";
    };
    date = "2025-05-25";
  };
  ulauncher-albert-calculate-anything = {
    pname = "ulauncher-albert-calculate-anything";
    version = "037965a44e6f6f496e7ad71ec1651b9edfcde32d";
    src = fetchFromGitHub {
      owner = "tchar";
      repo = "ulauncher-albert-calculate-anything";
      rev = "037965a44e6f6f496e7ad71ec1651b9edfcde32d";
      fetchSubmodules = false;
      sha256 = "sha256-RUxkStLxM8wg4a5yicoQCTjLxSEsb3HQwDSwrQicc2U=";
    };
    date = "2024-05-29";
  };
  ulauncher-colorconverter = {
    pname = "ulauncher-colorconverter";
    version = "2d5e2bc17e89f1f1dc561f73e68ea574e0be844a";
    src = fetchFromGitHub {
      owner = "sergius02";
      repo = "ulauncher-colorconverter";
      rev = "2d5e2bc17e89f1f1dc561f73e68ea574e0be844a";
      fetchSubmodules = false;
      sha256 = "sha256-UfRU7BpQUj26THzE8kYLIRUfe7voGvAcGDBTsl+yCwU=";
    };
    date = "2020-12-06";
  };
  ulauncher-emoji = {
    pname = "ulauncher-emoji";
    version = "af5806625e361ca4519b99755ccf0a557c1e894a";
    src = fetchFromGitHub {
      owner = "Ulauncher";
      repo = "ulauncher-emoji";
      rev = "af5806625e361ca4519b99755ccf0a557c1e894a";
      fetchSubmodules = false;
      sha256 = "sha256-wc4UP3Tf9osYr2bLvXTvfpAxb40qGH12o9qIB3En4Sg=";
    };
    date = "2025-06-03";
  };
  ulauncher-kill = {
    pname = "ulauncher-kill";
    version = "00ffe8266dbb6c2aea7d86a6363e51cec4b1981f";
    src = fetchFromGitHub {
      owner = "Ulauncher";
      repo = "ulauncher-kill";
      rev = "00ffe8266dbb6c2aea7d86a6363e51cec4b1981f";
      fetchSubmodules = false;
      sha256 = "sha256-37XvKa+aD7W9yHxXQng0gtW87YDIDybRQEX5Tw426QQ=";
    };
    date = "2022-11-26";
  };
  ulauncher-meme-my-text = {
    pname = "ulauncher-meme-my-text";
    version = "5d62830a7a92983a731e15645831f53d48dad913";
    src = fetchFromGitHub {
      owner = "RNairn01";
      repo = "ulauncher-meme-my-text";
      rev = "5d62830a7a92983a731e15645831f53d48dad913";
      fetchSubmodules = false;
      sha256 = "sha256-vIWIl2qOWYVrCLhGoDXH4xTfhc+GhE9cVFuV1qjYaH0=";
    };
    date = "2021-05-07";
  };
  ulauncher-tldr = {
    pname = "ulauncher-tldr";
    version = "2e5904451bf89dfa155280dfb6fa3d45ed4cab4c";
    src = fetchFromGitHub {
      owner = "dhelmr";
      repo = "ulauncher-tldr";
      rev = "2e5904451bf89dfa155280dfb6fa3d45ed4cab4c";
      fetchSubmodules = false;
      sha256 = "sha256-B/17gbGFUar2+PVfVQWZc7Eq8zADK4CeGW3XHQMqiAg=";
    };
    date = "2023-07-29";
  };
  ulauncher-virtualbox = {
    pname = "ulauncher-virtualbox";
    version = "d8f495df3c7f41ee8493b207d17f06fc0372c84e";
    src = fetchFromGitHub {
      owner = "luispabon";
      repo = "ulauncher-virtualbox";
      rev = "d8f495df3c7f41ee8493b207d17f06fc0372c84e";
      fetchSubmodules = false;
      sha256 = "sha256-IT1qsXpwYkl5vKGEBI9WySpWm6zOfe9ewj5oNgC8/Ro=";
    };
    date = "2020-09-23";
  };
  ulauncher-vscode-recent = {
    pname = "ulauncher-vscode-recent";
    version = "60a5106821478f965e4e24dbe1833f6af0d437f1";
    src = fetchFromGitHub {
      owner = "plibither8";
      repo = "ulauncher-vscode-recent";
      rev = "60a5106821478f965e4e24dbe1833f6af0d437f1";
      fetchSubmodules = false;
      sha256 = "sha256-sJJzHXp8S/Powqz0FgSCqfWL81q/mXqBi1KucRFB2LE=";
    };
    date = "2023-12-01";
  };
  yourls = {
    pname = "yourls";
    version = "1.10.1";
    src = fetchFromGitHub {
      owner = "YOURLS";
      repo = "YOURLS";
      rev = "1.10.1";
      fetchSubmodules = false;
      sha256 = "sha256-frOuwLMwe01no7aWmho6mn5jmiadydse3+ipR9VRoKc=";
    };
  };
  yourls-404-if-not-found = {
    pname = "yourls-404-if-not-found";
    version = "a611040c6f33cd6d00b07ddb824b9842ed2de2de";
    src = fetchFromGitHub {
      owner = "YOURLS";
      repo = "404-if-not-found";
      rev = "a611040c6f33cd6d00b07ddb824b9842ed2de2de";
      fetchSubmodules = false;
      sha256 = "sha256-3pgk7TkwuuTYz7eU9lxptkpqu0COOrWKZyt7Lp8VqLQ=";
    };
    date = "2023-12-16";
  };
  yourls-always-302 = {
    pname = "yourls-always-302";
    version = "c704f3d285fae60e0c49445c499a5bf4b235d411";
    src = fetchFromGitHub {
      owner = "tinjaw";
      repo = "Always-302";
      rev = "c704f3d285fae60e0c49445c499a5bf4b235d411";
      fetchSubmodules = false;
      sha256 = "sha256-llZagwjVWSXCupIzDQ90Rid6icKQ3PL5xoqIC0NzImg=";
    };
    date = "2020-08-22";
  };
  yourls-dont-track-admins = {
    pname = "yourls-dont-track-admins";
    version = "be87e385a52fb452d6b8c70e9fc28ca060a63f62";
    src = fetchFromGitHub {
      owner = "dgw";
      repo = "yourls-dont-track-admins";
      rev = "be87e385a52fb452d6b8c70e9fc28ca060a63f62";
      fetchSubmodules = false;
      sha256 = "sha256-GWCUpxPfD/bqwGS1Rhu12HVDK7hgQVCv2mlcI5OOvUg=";
    };
    date = "2022-05-30";
  };
  yourls-login-timeout = {
    pname = "yourls-login-timeout";
    version = "1a8eee5a5104c15660952abc49b79486d81917c6";
    src = fetchFromGitHub {
      owner = "reanimus";
      repo = "yourls-login-timeout";
      rev = "1a8eee5a5104c15660952abc49b79486d81917c6";
      fetchSubmodules = false;
      sha256 = "sha256-YGz09e2Fd9R1LcXVIGSjvlF7Hzn6KLB2ZiTL/jPlkSA=";
    };
    date = "2019-04-01";
  };
  yourls-sleeky = {
    pname = "yourls-sleeky";
    version = "8c1dcd8f320c5415eb6c49863f6c836e527b1ca2";
    src = fetchFromGitHub {
      owner = "Flynntes";
      repo = "Sleeky";
      rev = "8c1dcd8f320c5415eb6c49863f6c836e527b1ca2";
      fetchSubmodules = false;
      sha256 = "sha256-l6znBrtNYwCWX3ef5qaT5ErC0IKKG3+GAzF+h7Klme0=";
    };
    date = "2025-02-17";
  };
}
