# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, ... }:
{
  boot.loader.grub = {
    efiSupport = true;
    device = "nodev";
  };

  networking.usePredictableInterfaceNames = lib.mkForce true;

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/317D-D6BD";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/16345591-4ea5-4cc6-a1ef-04f1eed48916";
    fsType = "btrfs";
    options = [
      "compress-force=zstd"
      "nosuid"
      "nodev"
    ];
  };

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableRedistributableFirmware = true;
}
