# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ ... }:
{
  imports = [
    ../../nixos/hardware/disable-watchdog.nix
    ../../nixos/hardware/nvidia/cuda-only.nix
    ../../nixos/hardware/nvidia/grid-extension.nix
    ../../nixos/hardware/qemu.nix
    ../../nixos/hardware/qemu-hotplug.nix
  ];

  boot.initrd.kernelModules = [ "virtiofs" ];

  boot.loader.grub.device = "/dev/vda";

  fileSystems."/nix" = {
    device = "virtiofs-nixos-home-vm";
    fsType = "virtiofs";
  };

  fileSystems."/mnt/storage" = {
    device = "/dev/vdb";
    fsType = "btrfs";
    options = [
      "compress-force=zstd"
      "autodefrag"
      "nosuid"
      "nodev"
      "x-systemd.mount-timeout=infinity"
    ];
    neededForBoot = true;
  };

  fileSystems."/mnt/ssd-temp" = {
    device = "/dev/vdc1";
    fsType = "ext4";
    options = [
      "discard"
      "nosuid"
      "nodev"
      "x-systemd.mount-timeout=infinity"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/22DA-8396";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  services.btrfs.autoScrub = {
    enable = true;
    fileSystems = [ "/mnt/storage" ];
  };

  services.qemuGuest.enable = true;
}
