# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, ... }:
{
  imports = [
    ../../nixos/hardware/disable-watchdog.nix
    ../../nixos/hardware/nvidia/cuda-only.nix
    ../../nixos/hardware/qemu-hotplug.nix
  ];

  boot.loader.grub.mirroredBoots = [
    {
      devices = [ "/dev/vda" ];
      path = "/nix/boot";
    }
  ];

  fileSystems."/nix" = {
    device = "/dev/vda1";
    fsType = "btrfs";
    options = [
      "compress-force=zstd"
      "nosuid"
      "nodev"
    ];
  };

  fileSystems."/mnt/storage" = {
    device = "/dev/vdb";
    fsType = "btrfs";
    options = [
      "compress-force=zstd"
      "nosuid"
      "nodev"
      "x-systemd.mount-timeout=infinity"
    ];
    neededForBoot = true;
  };

  fileSystems."/boot" = {
    device = "/nix/boot";
    options = [ "bind" ];
  };

  services.btrfs.autoScrub = {
    enable = true;
    fileSystems = [ "/mnt/storage" ];
  };

  services.qemuGuest.enable = true;

  swapDevices = [
    {
      device = "/dev/vda2";
      randomEncryption.enable = true;
    }
  ];

  systemd.services.nvidia-power-limit = {
    description = "Set Power Limit for NVIDIA GPUs";
    wantedBy = [ "multi-user.target" ];
    path = [ config.hardware.nvidia.package ];
    script = ''
      DATETIME=$(date '+%H%M')
      if [ "$DATETIME" -lt "0900" ]; then
        nvidia-smi -pl 150
      elif [ "$DATETIME" -lt "2200" ]; then
        nvidia-smi -pl 250
      else
        nvidia-smi -pl 150
      fi
    '';
    serviceConfig.Type = "oneshot";
  };

  systemd.timers.nvidia-power-limit = {
    wantedBy = [ "timers.target" ];
    partOf = [ "nvidia-power-limit.service" ];
    timerConfig = {
      OnCalendar = "minutely";
      Unit = "nvidia-power-limit.service";
    };
  };
}
