# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  boot.loader.grub.device = "/dev/sda";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/DADA-BCDD";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/989c547c-e0ba-4aef-9961-cb5fbbefcc35";
    fsType = "btrfs";
    options = ["compress-force=zstd" "nosuid" "nodev"];
  };
}
