# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, lib, modulesPath, ... }:

{
  imports = [
    ../../nixos/hardware/general.nix
  ];

  boot.loader.grub.devices = [
    "/dev/sda"
    "/dev/sdb"
  ];

  boot.initrd.kernelModules = [
    "dm-raid"
    "dm-integrity"
    "raid0"
    "raid1"
    "raid10"
    "raid456"
  ];

  services.lvm.dmeventd.enable = true;

  fileSystems."/nix" = {
    device = "/dev/mapper/MyVolGroup-root";
    fsType = "btrfs";
    options = [ "compress-force=zstd" "nosuid" "nodev" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0E72-608D";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  # fileSystems."/boot/esp1" = {
  #   device = "/dev/disk/by-uuid/22B6-EB16";
  #   fsType = "vfat";
  #   options = [ "fmask=0077" "dmask=0077" ];
  # };

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
