{ config, LT, ... }:
{
  imports = [ ./postgresql.nix ];

  services.postgresql = {
    ensureDatabases = [ "maddy" ];
    ensureUsers = [
      {
        name = "maddy";
        ensureDBOwnership = true;
      }
    ];
  };

  services.maddy = {
    enable = true;
    hostname = "${config.networking.hostName}.lantian.dn42";
    primaryDomain = "lantian.dn42";
    localDomains = [
      "lantian.dn42"
      "lantian.neo"
    ];

    tls = {
      loader = "file";
      certificates =
        builtins.map
          (v: {
            certPath = LT.nginx.getSSLCert v;
            keyPath = LT.nginx.getSSLKey v;
          })
          [
            "zerossl-lantian.pub-ecc"
            "zerossl-xuyh0120.win-ecc"
            "dn42-lantian.dn42-ecc"
          ];
    };

    config = ''
      auth.pass_table local_authdb {
        table sql_table {
          driver postgres
          dsn postgres:///maddy?host=/run/postgresql&user=maddy
          table_name passwords
        }
      }

      storage.imapsql local_mailboxes {
        driver postgres
        dsn postgres:///maddy?host=/run/postgresql&user=maddy
      }

      table.chain local_rewrites {
        optional_step regexp "(.+)\+(.+)@(.+)" "$1@$3"
        optional_step file /etc/maddy/aliases
      }

      msgpipeline local_routing {
        destination $(local_domains) {
          modify {
            replace_rcpt &local_rewrites
          }
          deliver_to &local_mailboxes
        }
        default_destination {
          reject 550 5.1.1 "User doesn't exist"
        }
      }

      smtp tcp://[::]:25 {
        limits {
          all rate 20 1s
          all concurrency 10
        }
        dmarc yes
        check {
          require_mx_record
          dkim
          spf
        }
        source $(local_domains) {
          reject 501 5.1.8 "Use Submission for outgoing SMTP"
        }
        default_source {
          destination $(local_domains) {
            deliver_to &local_routing
          }
          default_destination {
            reject 550 5.1.1 "User doesn't exist"
          }
        }
      }

      submission tcp://[::]:587 {
        limits {
          all rate 50 1s
        }
        auth &local_authdb
        source $(local_domains) {
          check {
              authorize_sender {
                  prepare_email &local_rewrites
                  user_to_email identity
              }
          }
          destination $(local_domains) {
              deliver_to &local_routing
          }
          default_destination {
              modify {
                  dkim $(primary_domain) $(local_domains) default
              }
              deliver_to &remote_queue
          }
        }
        default_source {
          reject 501 5.1.8 "Non-local sender domain"
        }
      }

      target.remote outbound_delivery {
        limits {
          destination rate 20 1s
          destination concurrency 10
        }
        mx_auth {
          dane
          mtasts {
            cache fs
            fs_dir mtasts_cache/
          }
          local_policy {
              min_tls_level encrypted
              min_mx_level none
          }
        }
      }

      target.queue remote_queue {
        target &outbound_delivery
        autogenerated_msg_domain $(primary_domain)
        bounce {
          destination $(local_domains) {
            deliver_to &local_routing
          }
          default_destination {
              reject 550 5.0.0 "Refusing to send DSNs to non-local addresses"
          }
        }
      }

      imap tcp://[::]:143 {
        auth &local_authdb
        storage &local_mailboxes
      }
    '';
  };

  systemd.services.maddy = {
    after = [ "postgresql.service" ];
    requires = [ "postgresql.service" ];
  };
}
