# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
_: {

  boot.loader.grub.device = "/dev/sda"; # or "nodev" for efi only

  fileSystems."/nix" = {
    device = "/dev/sda2";
    fsType = "btrfs";
    options = [
      "compress-force=zstd"
      "nosuid"
      "nodev"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/sda1";
    fsType = "ext4";
  };
}
