# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, lib, modulesPath, ... }:

{
  imports = [
    ../../nixos/hardware/general.nix
  ];

  boot.loader.grub = {
    efiSupport = true;
    mirroredBoots = [
      { devices = [ "nodev" ]; path = "/boot/esp0"; }
      { devices = [ "nodev" ]; path = "/boot/esp1"; }
      { devices = [ "nodev" ]; path = "/boot/esp2"; }
      { devices = [ "nodev" ]; path = "/boot/esp3"; }
    ];
  };
  boot.loader.efi.efiSysMountPoint = "/boot/EFI";

  boot.initrd.kernelModules = [
    "dm-raid"
    "dm-integrity"
    "raid0"
    "raid1"
    "raid10"
    "raid456"
  ];

  services.lvm.dmeventd.enable = true;

  fileSystems."/nix" = {
    device = "/dev/mapper/MyVolGroup-root";
    fsType = "btrfs";
    options = [ "compress-force=zstd" "nosuid" "nodev" ];
  };

  fileSystems."/boot/esp0" = {
    device = "/dev/disk/by-uuid/1415-5827";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/boot/esp1" = {
    device = "/dev/disk/by-uuid/143C-186E";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/boot/esp2" = {
    device = "/dev/disk/by-uuid/144A-CCED";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/boot/esp3" = {
    device = "/dev/disk/by-uuid/145A-606D";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
