logger:
  file:
    path: /var/log/open5gs/scp.log
#  level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

scp:
  sbi:
    server:
      - address: 127.0.0.200
        port: 7777
    client:
      nrf:
        - uri: http://127.0.0.10:7777

################################################################################
# SCP Info
################################################################################
#  o SCP port number(s) WITHOUT SCP Domain
#   - If no SCP port information is present in ScpInfo or
#     in ScpDomainInfo for a specific SCP domain,
#     the HTTP client shall use the default HTTP port number,
#     i.e. TCP port 80 for "http" URIs or TCP port 443
#     for "https" URIs as specified in IETF RFC 7540 [9]
#     when sending a request to the SCP within the specific SCP domain.
#  info:
#    port:
#      http: 7777
#      https: 8888
#
#  o SCP port number(s) WITH SCP Domain
#   - If this attribute is present,
#     it has precedence over the scpPorts attribute of ScpInfo.
#  info:
#    domain:
#      - name: SCP_Domain_1
#        fqdn: scp.epc.mnc010.mcc315.3gppnetwork.org
#        port:
#          http: 7777
#          https: 8888
#
#  o Complex Example
#  info:
#    port:
#      http: 7777
#      https: 8888
#    domain:
#      - name: SCP_Domain_1
#        fqdn: scp.hplmndomain
#        port:
#          http: 3333
#          https: 4444
#      - name: SCP_Domain_2
#        fqdn: scp.vplmndomain
#        port:
#          http: 5555
#          https: 6666
#
################################################################################
# SBI Server
################################################################################
#  o Override SBI address to be advertised to NRF
#  sbi:
#    server:
#      - dev: eth0
#        advertise: open5gs-scp.svc.local
#
#  sbi:
#    server:
#      - address: localhost
#        advertise:
#          - 127.0.0.99
#          - ::1
#
################################################################################
# SBI Client
################################################################################
#  o Direct communication with NRF interaction
#  sbi:
#    client:
#      nrf:
#        - uri: http://127.0.0.10:7777
#
################################################################################
# HTTPS scheme with TLS
################################################################################
#  o Set as default if not individually set
#  default:
#    tls:
#      server:
#        scheme: https
#        private_key: /var/lib/open5gs-certs/scp.key
#        cert: /var/lib/open5gs-certs/scp.crt
#      client:
#        scheme: https
#        cacert: /var/lib/open5gs-certs/ca.crt
#  sbi:
#    server:
#      - address: scp.epc.mnc010.mcc315.3gppnetwork.org
#    client:
#      nrf:
#        - uri: https://nrf.epc.mnc010.mcc315.3gppnetwork.org
#
#  o Add client TLS verification
#  default:
#    tls:
#      server:
#        scheme: https
#        private_key: /var/lib/open5gs-certs/scp.key
#        cert: /var/lib/open5gs-certs/scp.crt
#        verify_client: true
#        verify_client_cacert: /var/lib/open5gs-certs/ca.crt
#      client:
#        scheme: https
#        cacert: /var/lib/open5gs-certs/ca.crt
#        client_private_key: /var/lib/open5gs-certs/scp.key
#        client_cert: /var/lib/open5gs-certs/scp.crt
#  sbi:
#    server:
#      - address: scp.epc.mnc010.mcc315.3gppnetwork.org
#    client:
#      nrf:
#        - uri: https://nrf.epc.mnc010.mcc315.3gppnetwork.org
