# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    ../../nixos/hardware/general.nix
  ];

  boot.loader.grub = {
    efiSupport = true;
    efiInstallAsRemovable = true;
    device = "nodev";
    gfxmodeBios = "2560x1440x32,auto";
    gfxmodeEfi = "2560x1440x32,auto";
    useOSProber = true;
  };

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" ];

  boot.initrd.luks.devices."root" = {
    allowDiscards = true;
    bypassWorkqueues = true;
    device = "/dev/disk/by-uuid/23390759-5d5a-4708-8eeb-f72430c3274c";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B406-5B9F";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = [ "subvol=home" "compress-force=zstd" ];
  };

  fileSystems."/home/lantian/Downloads" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = [ "subvol=downloads-lantian" "compress-force=zstd" ];
  };

  fileSystems."/mnt/c" = {
    device = "/dev/disk/by-uuid/8C60FBA460FB92E6";
    fsType = "ntfs3";
    options = [ "prealloc" "uid=1000" "gid=1" "fmask=0077" "dmask=0077" "discard" "nofail" ];
  };

  fileSystems."/mnt/root" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = [ "compress-force=zstd" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = [ "subvol=nix" "compress-force=zstd" ];
  };

  swapDevices = [{
    device = "/dev/disk/by-partuuid/6a423fb7-a6b9-934c-b587-246c03066e9f";
    discardPolicy = "both";
    randomEncryption = {
      enable = true;
      allowDiscards = true;
    };
  }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableRedistributableFirmware = true;
}
