name: auto-push

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  auto-push:
    name: Auto push to private repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://github.com/cpina/github-action-push-to-another-repository/issues/75
      - name: Fix repository not found error
        run: |
          git config --unset-all http.https://github.com/.extraheader

      - uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTOMERGE_TOKEN }}
        with:
          source-directory: '.'
          destination-github-username: 'xddxdd'
          destination-repository-name: 'nixos-config-private-copy'
          user-email: 'xuyh0120+github-bot@outlook.com'
          user-name: 'xddxdd-bot'
          create-target-branch-if-needed: true
