name: auto-push

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  auto-push:
    name: Auto push to private repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - env:
          API_TOKEN_GITHUB: ${{ secrets.AUTOMERGE_TOKEN }}
        run: |
          # https://github.com/cpina/github-action-push-to-another-repository/issues/75
          git config --unset-all http.https://github.com/.extraheader
          git remote add private https://xddxdd-bot:$API_TOKEN_GITHUB@github.com/xddxdd/nixos-config-private-copy.git
          git push -u private master --force
