name: auto-push

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '55 5 * * *'

jobs:
  auto-push:
    name: Auto push to private repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Install nix
        uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.AUTOMERGE_TOKEN }}
          extra_nix_config: |
            extra-platforms = i686-linux aarch64-linux arm-linux

      - name: Build nix packages
        run: |
          cat > secrets.toml <<EOF
          [keys]
          github = "${{ secrets.AUTOMERGE_TOKEN }}"
          EOF

          nix run .#update

          rm -f secrets.toml

      - env:
          API_TOKEN_GITHUB: ${{ secrets.AUTOMERGE_TOKEN }}
        run: |
          # https://github.com/cpina/github-action-push-to-another-repository/issues/75
          git config --unset-all http.https://github.com/.extraheader
          git config --global user.email "xddxdd@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git add . || true
          git commit -m "auto: update packages" || true
          git remote add private "https://xddxdd-bot:$API_TOKEN_GITHUB@github.com/xddxdd/nixos-config-private-copy.git"
          git push -u private master --force
